### ISSUE TITLE
less foo.zip:non-existent-file does not fail when LESSCOLORIZER=pygmentize

### ISSUE THREAD

**Issue by anntzer** [wofr06/lesspipe#1] opened 2015-08-27 09:00 UTC
All's in the title.
When LESSCOLORIZER is unset, less foo.zip:non-existent-file correctly fails with "No such file or directory".  When it is set to pygmentize, an empty file is apparently passed to less.

**Comment by wofr06** [comment] 2015-08-28 08:29
On Thu, 27 Aug 2015, Antony Lee wrote:

> 
> All's in the title.
> When LESSCOLORIZER is unset, less foo.zip:non-existent-file correctly fails with "No such file or directory". When it is set to pygmentize, an empty file is apparently passed to
> less.
> 
> —
> Reply to this email directly or view it on GitHub.[AMwlQGcv8nD3pVxg2mAU5uKjcL5JP5qIks5orslJgaJpZM4FzKu_.gif]
> 
Dear Antony,

seems to be easily correctable. I'll take care during the weekend. Thanks 
for reporting it.

Best, Wolfgang

**Comment by wofr06** [comment] 2015-09-01 09:28
On Thu, 27 Aug 2015, Antony Lee wrote:

Dear Antony,

I tried both with and without pygmentize (versions 1.6 and 2.0.2) and with 
an existing foo.zip and non existing non-existent-file in the zip file. In 
all cases I got the correct answer

foo.zip:non-existent-file: No such file or directory

The only explanation I have is that your version of pygmentize or some 
command executed by default (e.g. in .bashrc or /etc/bashrc) is producing 
some output (an empty line). But in the latter case this should even 
happen with

less non-existent-file

nevertheless I found a flaw in code2color:

diff --git a/code2color b/code2color
index a3608fa..7164d75 100755
--- a/code2color
+++ b/code2color
@@ -3259,7 +3259,7 @@ getopts('i:l:') || exit 2;
        if ! -x $ENV{LESSCOLORIZER}
        and ! grep { -x "$_/$ENV{LESSCOLORIZER}" } split /:/, $ENV{PATH};
      # call external colorizer
-    if ($ENV{LESSCOLORIZER} eq 'pygmentize') {
+    if (basename($ENV{LESSCOLORIZER}) eq 'pygmentize') {
        # do not call pygmentize with - and use option -g
        @ARGV = grep {$_ ne '-'} @ARGV;
        unshift @ARGV, '-g';

which I will check in soon. Do you have still any idea how I could 
reproduce your misbehaving lesspipe?

Best, Wolfgang

**Comment by anntzer** [comment] 2015-09-01 17:13
I get the same in the `sh` shell (so there shouldn't be any hidden rcfile involved), and am using pygmentize 2.0.2.  Moreover, `pygmentize non-existent-file` correctly prints an error on stderr.  I'll investigate.

**Comment by wofr06** [comment] 2015-09-01 17:29
On Tue, 1 Sep 2015, Antony Lee wrote:

> 
> I get the same in the sh shell (so there shouldn't be any hidden rcfile
> involved), and am using pygmentize 2.0.2. Moreover, pygmentize
> non-existent-file correctly prints an error on stderr. I'll investigate.

Interestingly I can reproduce this behavior on an Ubuntu 15.04 system but 
not on a SL6 machine. Now having a system that shows the symptom I should 
be able to fix it.

Cheers, Wolfgang

**Comment by wofr06** [comment] 2015-09-03 17:11
The problem was due to different behaviour of the 'file' command for Ubuntu and RHEL6/SL6.
The change has been checked in. The similar problem of incorrectly reporting empty files in archives as non existent is however not fixed yet.

**Closed by wofr06** 2015-09-03 17:11 UTC
